import LeftSidebar from '@/components/homepage/news/LeftSidebar';
import NewsCard from '@/components/homepage/news/NewsCard';
import RightSidebar from '@/components/homepage/news/RightSidebar';
import { getCategories, getNewsByCategoryId } from '@/lib/data';
import React from 'react';

export const metadata = {
  title: "Dragon News",
  description: "Generated by create next app",
};

const NewsCategoryPage =async ({params}) => {
    const {id} = await params
    console.log({id})
     const categories = await getCategories();
  //  console.log(categories)
  const news = await getNewsByCategoryId(id);
  //  console.log(news)
    return (
        <div className="grid grid-cols-12 gap-4 container mx-auto my-10">
          <div className="col-span-3">
            <LeftSidebar categories={categories} isActiveId={id}></LeftSidebar>
          </div>
          <div className="col-span-6">
            <h2 className='p-1 font-bold text-xl'>Dragon News Home</h2>
            <div className='space-y-4'>
              {news.length > 0 ? ( news.map((n)=> {
                  return (
                  <NewsCard key={n._id} n={n}></NewsCard>
                   );
                })
            ) : (
            <h2 className=' font-bold text-4xl text-center my-5'>No news Founds!</h2>
             )}
            </div>
          </div>
          <div className="col-span-3">
            <RightSidebar></RightSidebar>
          </div>
      </div>
    );
};

export default NewsCategoryPage;