import { redirect } from "next/navigation";
export const metadata = {
  title: "Dragon News-Home",
  description: "Generated by create next app",
};

const default_category_id =  "01"
export default async function Home () {
   redirect(`category/${default_category_id}`)
 
}
