import React from 'react';

export const metadata = {
  title: "Dragon News-About",
  description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            about
        </div>
    );
};

export default page;